Repository Galindo1327/NovaMarket, pull requests merged in 2024-11, with the labels that each got.

#18 Feature: Deleting dark mode
  index.html
  src/App.jsx
  src/components/Feed.jsx
Labels: Feature

#15 NovaMarket V1.1.0
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Bmw.jpg
  src/assets/Cicla.jpg
  src/assets/Ducati.avif
  src/assets/Horno.jpg
  src/assets/Iphone.jpg
  src/assets/LavadoraSec.avif
  src/assets/Mcbook.webp
  src/assets/Nevera.jpg
  src/assets/Nikon.jpg
  src/assets/Samsung.png
  src/assets/Sony.jpg
  src/assets/Tv.png
  src/assets/logoNova.png
  src/components/AddProduct.jsx
  src/components/Calificacion.jsx
  src/components/ComponentePadre.jsx
  src/components/DetalleProducto.css
  src/components/DetalleProducto.jsx
  src/components/Feed.css
  src/components/Feed.jsx
  src/components/Perfil.jsx
  src/components/PerfilSeguir.jsx
  src/credentials.js
  src/pages/Home.css
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: documentation, Feature

#19 punto 5 y 6, visual header y agg button regresar
  src/components/AddProduct.jsx
  src/components/DetalleProducto.jsx
  src/components/Perfil.jsx
  src/components/PerfilSeguir.jsx
  src/pages/Register.jsx
Labels: Feature

#23 Implentacion del Nombre en register, Correccio Filtro y Arreglo visual Feed
  src/App.jsx
  src/components/DetalleProducto.jsx
  src/components/Feed.css
  src/components/Feed.jsx
  src/context/authContext.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: Feature

#25 fix: Current User Display Name / feat: Current User now can add product and appear in product detail
  src/components/AddProduct.jsx
  src/components/DetalleProducto.jsx
  src/context/authContext.jsx
Labels: Bug, Feature

#24 Correcion Color Header, logo, direccionamiento al feed.
  src/components/DetalleProducto.jsx
  src/components/PerfilSeguir.jsx
Labels: Feature

#26 feat: Adding chat page
  src/App.jsx
  src/components/DetalleProducto.jsx
  src/components/Feed.jsx
  src/pages/Chat.jsx
  src/pages/Login.jsx
Labels: Bug, Feature

#21 Se ha actualizado la vista Perfil y Perfil Seguir funcional.
  src/assets/dondimadon.png
  src/components/DetalleProducto.jsx
  src/components/Perfil.jsx
  src/components/PerfilSeguir.jsx
  src/credentials.js
Labels: Feature

#27 feat: User ID when adding a product / fix: User Info appear in "perfil usuario"
  src/components/AddProduct.jsx
  src/components/DetalleProducto.jsx
  src/components/PerfilSeguir.jsx
Labels: Bug, Feature

#28 fix: App Styles
  src/components/AddProduct.jsx
  src/components/Calificacion.jsx
  src/components/ComponentePadre.jsx
  src/components/DetalleProducto.jsx
  src/components/Feed.jsx
  src/components/Perfil.jsx
  src/components/PerfilSeguir.jsx
  src/pages/Chat.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: Bug

#20 Test to master
  src/App.jsx
  src/assets/dondimadon.png
  src/components/AddProduct.jsx
  src/components/Calificacion.jsx
  src/components/ComponentePadre.jsx
  src/components/DetalleProducto.jsx
  src/components/Feed.css
  src/components/Feed.jsx
  src/components/Perfil.jsx
  src/components/PerfilSeguir.jsx
  src/context/authContext.jsx
  src/credentials.js
  src/pages/Chat.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: documentation, Feature

#31 Puntos 3,4,5,6,7
  src/components/AddProduct.jsx
  src/components/DetalleProducto.jsx
  src/components/Feed.jsx
Labels: Feature

#32 Cambios en el registro y visualización de comentarios
  src/components/Calificacion.jsx
  src/components/Perfil.jsx
  src/context/authContext.jsx
  src/pages/Register.jsx
Labels: Feature
